/// Stable, client-generated identifier of a session.
///
/// Generated once when the session is created and never reassigned, so that a
/// later backup and restore can reconcile identity rather than duplicate it.
extension type const SessionId(String value) {}

/// Stable, client-generated identifier of a reading.
///
/// See [SessionId] for why identity is generated by the client.
extension type const ReadingId(String value) {}
